name: Deploy on GitHub Pages

on:
    push:
        branches: [main]

jobs:
    deploy-on-github-pages:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  target: wasm32-unknown-unknown
                  override: true

            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Build
              run: |
                  cargo build --release --target wasm32-unknown-unknown
                  mkdir -p ./dist
                  cp -r \
                    ./src/index.html \
                    ./assets \
                    ./target/wasm32-unknown-unknown/release/deathball.wasm \
                    ./dist
                  curl https://raw.githubusercontent.com/not-fl3/miniquad/v0.3.0-alpha.37/native/sapp-wasm/js/gl.js \
                      --output ./dist/gl.js

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  branch: gh-pages
                  folder: ./dist
